using System.Text.Json;
using AI.Investment.Domain.Analytics;
using AI.Investment.Domain.Analytics.Financial;
using AI.Investment.Domain.Analytics.Scoring;
using AI.Investment.Domain.Enums;
using AI.Investment.Domain.UnitTests.Analytics.Financial;
using AI.Investment.Domain.ValueObjects;
using Xunit;

namespace AI.Investment.Domain.UnitTests.Analytics.Scoring;

/// <summary>
/// The reproducibility gate: a stored bundle of reported figures must produce the stored score,
/// exactly, and every number in that score must trace back to a claim.
/// </summary>
/// <remarks>
/// <para>
/// This is what makes a score worth storing. A number that cannot be re-derived from the evidence
/// it claims to rest on is an opinion with a decimal point, and a scoring specification whose
/// weights can drift without anyone noticing produces a series that is not comparable with itself
/// over time.
/// </para>
/// <para>
/// The golden file holds the inputs, the expected score, and each component's raw and normalised
/// value. It is deliberately not regenerated by the test: if the arithmetic changes, this fails,
/// and the correct response is to decide whether the change was intended and bump the
/// specification version - not to overwrite the file.
/// </para>
/// </remarks>
public sealed class ScoringGoldenFileTests
{
    private static readonly string GoldenPath =
        Path.Combine(AppContext.BaseDirectory, "Golden", "financial-health-v1.json");

    [Fact]
    public void The_golden_bundle_is_shipped_beside_the_tests() =>
        Assert.True(
            File.Exists(GoldenPath),
            $"The golden bundle was not found at {GoldenPath}. It is copied to the output directory " +
            "by the test project; without it this gate silently tests nothing.");

    [Fact]
    public void A_stored_bundle_reproduces_the_stored_score()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(GoldenPath));
        var golden = document.RootElement;

        var context = Financials.Context();
        var score = Score(context, Bundle(golden));

        Assert.Equal(golden.GetProperty("score").GetString(), score.Metric.Value);
        Assert.Equal(golden.GetProperty("specificationVersion").GetString(), score.Version.ToString());
        Assert.Equal(golden.GetProperty("value").GetDecimal(), score.Value.Amount);

        // The file records full coverage, and a fully covered score carries no caveats.
        Assert.Equal(1m, golden.GetProperty("coverage").GetDecimal());
        Assert.Empty(score.Caveats);
    }

    [Fact]
    public void Every_component_matches_the_stored_raw_and_normalised_value()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(GoldenPath));
        var golden = document.RootElement;

        var context = Financials.Context();
        var score = Score(context, Bundle(golden));
        var components = golden.GetProperty("components").EnumerateArray().ToList();

        Assert.Equal(components.Count, score.Inputs.Count);

        foreach (var component in components)
        {
            var metric = component.GetProperty("metric").GetString()!;

            var input = Assert.Single(score.Inputs, candidate => candidate.Name == metric);

            Assert.Equal(component.GetProperty("raw").GetDecimal(), input.Value);

            // Re-applies the shipped normalisation, so a silent edit to a declared range fails here
            // rather than quietly changing the meaning of every score already stored.
            var declared = Assert.Single(
                ScoringSpecifications.FinancialHealthV1.Components,
                candidate => candidate.Metric.Value == metric);

            Assert.Equal(
                component.GetProperty("normalised").GetDecimal(),
                declared.Normalisation.Apply(input.Value));
        }
    }

    /// <summary>Same bundle, same cutoff, same number - every time, or none of this is replayable.</summary>
    [Fact]
    public void Scoring_the_same_bundle_twice_gives_the_same_number()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(GoldenPath));
        var golden = document.RootElement;

        var context = Financials.Context();

        var first = Score(context, Bundle(golden));
        var second = Score(context, Bundle(golden));

        Assert.Equal(first.Value.Amount, second.Value.Amount);
        Assert.Equal(first.AsOfUtc, second.AsOfUtc);
        Assert.Equal(first.Version, second.Version);

        Assert.Equal(
            first.Inputs.Select(input => $"{input.Name}={input.Value}"),
            second.Inputs.Select(input => $"{input.Name}={input.Value}"));
    }

    /// <summary>
    /// The exit criterion in the roadmap: every score input is a traceable claim. Each component is
    /// a calculation, and each of those names the observed facts underneath it.
    /// </summary>
    [Fact]
    public void Every_score_input_traces_back_to_observed_evidence()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(GoldenPath));

        var context = Financials.Context();
        var score = Score(context, Bundle(document.RootElement));

        foreach (var input in score.Inputs)
        {
            Assert.Equal(ClaimKind.Calculation, input.Evidence.Kind);
            Assert.NotEmpty(input.Evidence.DerivedFrom);
            Assert.Equal(score.CalculatorId, score.ToClaim().Provenance.SourceId);
        }

        Assert.Equal(score.Inputs.Count, score.ToClaim().DerivedFrom.Count);
    }

    private static ReportedFigures Bundle(JsonElement golden) =>
        ReportedFigures.Create(
            Financials.Subject,
            Financials.CurrentPeriodEnd,
            Currency.Usd,
            golden.GetProperty("bundle")
                .EnumerateObject()
                .Select(figure => Financials.Money(figure.Name, figure.Value.GetDecimal())));

    /// <summary>
    /// Runs the real financial calculators over the bundle and scores the results, including the
    /// chained free-cash-flow margin, so the gate covers the whole path rather than the engine alone.
    /// </summary>
    private static MetricResult Score(CalculationContext context, ReportedFigures reported)
    {
        var freeCashFlow = FinancialCalculators.FreeCashFlow.Calculate(context, reported).RequireResult();

        var enriched = reported.With(
            ReportedFigure.OfMoney(FinancialFigures.FreeCashFlow, freeCashFlow.ToClaim()));

        var components = new List<MetricResult>
        {
            FinancialCalculators.NetMargin.Calculate(context, enriched).RequireResult(),
            FinancialCalculators.CurrentRatio.Calculate(context, enriched).RequireResult(),
            FinancialCalculators.DebtToEquity.Calculate(context, enriched).RequireResult(),
            FinancialCalculators.FreeCashFlowMargin.Calculate(context, enriched).RequireResult(),
        };

        return ScoringSpecifications.FinancialHealthEngine
            .Calculate(context, components)
            .RequireResult();
    }
}
