// <auto-generated />
using System;
using AI.Investment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI.Investment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI.Investment.Domain.Actions.ActionExecution", b =>
                {
                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("ExecutionId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_action_executions_correlation_id");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("ix_action_executions_proposal_id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_action_executions_started_at_utc");

                    b.ToTable("action_executions", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Approvals.ApprovalToken", b =>
                {
                    b.Property<Guid>("ApprovalTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action_fingerprint");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.HasKey("ApprovalTokenId");

                    b.HasIndex("OpportunityId", "ConsumedAtUtc")
                        .HasDatabaseName("ix_approval_tokens_opportunity");

                    b.ToTable("approval_tokens", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("AuditRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("actor_kind");

                    b.Property<string>("Capability")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<string>("RiskTier")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("risk_tier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<string>("_details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.HasKey("AuditRecordId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_records_correlation_id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_occurred_at_utc");

                    b.HasIndex("ProposalId")
                        .HasDatabaseName("ix_audit_records_proposal_id");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Autonomy.AutonomyGrant", b =>
                {
                    b.Property<Guid>("AutonomyGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<DateTime?>("DemotedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("demoted_at_utc");

                    b.Property<string>("DemotedMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("demoted_mode");

                    b.Property<int>("DemotionCount")
                        .HasColumnType("integer")
                        .HasColumnName("demotion_count");

                    b.Property<string>("DemotionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("demotion_reason");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("environment");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("granted_by");

                    b.Property<string>("GrantedMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("granted_mode");

                    b.Property<string>("LimitSetName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("limit_set");

                    b.Property<string>("MaxRiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("max_risk_tier");

                    b.Property<Guid?>("PromotionWarrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_warrant_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.HasKey("AutonomyGrantId");

                    b.HasIndex("Capability", "EnvironmentName", "ExpiresAtUtc")
                        .HasDatabaseName("ix_autonomy_grants_lookup");

                    b.ToTable("autonomy_grants", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Autonomy.LiveVenueAuthorization", b =>
                {
                    b.Property<Guid>("LiveVenueAuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AuthorisedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorised_at_utc");

                    b.Property<string>("AuthorisedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("authorised_by");

                    b.Property<string>("CounterSignedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("counter_signed_by");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("environment");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("justification");

                    b.Property<Guid>("PromotionWarrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_warrant_id");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("venue_id");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("withdrawal_reason");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at_utc");

                    b.HasKey("LiveVenueAuthorizationId");

                    b.HasIndex("VenueId", "EnvironmentName")
                        .IsUnique()
                        .HasDatabaseName("ux_live_venue_authorizations_venue");

                    b.ToTable("live_venue_authorizations", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Autonomy.PromotionWarrant", b =>
                {
                    b.Property<Guid>("PromotionWarrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("BenchmarkFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("benchmark_fingerprint");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("environment");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("issued_by");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justification");

                    b.Property<string>("MaxMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("max_mode");

                    b.Property<string>("MaxRiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("max_risk_tier");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("ValidationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("validation_run_id");

                    b.HasKey("PromotionWarrantId");

                    b.HasIndex("Capability", "EnvironmentName", "ExpiresAtUtc")
                        .HasDatabaseName("ix_promotion_warrants_lookup");

                    b.ToTable("promotion_warrants", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Capital.LedgerEntry", b =>
                {
                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.HasKey("LedgerEntryId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_ledger_entries_occurred_at_utc");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_ledger_entries_opportunity");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Exchange")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("exchange");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_companies_name");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_ticker");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Ingestion.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RefusalRuleId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("refusal_rule_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("_artifacts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("artifacts");

                    b.HasKey("Id");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("ix_ingestion_runs_outcome");

                    b.HasIndex("RequestFingerprint")
                        .HasDatabaseName("ix_ingestion_runs_request_fingerprint");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_ingestion_runs_started_at_utc");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Normalization.QuarantinedPayload", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<DateTime>("QuarantinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quarantined_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("rule_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("QuarantinedAtUtc")
                        .HasDatabaseName("ix_quarantined_payloads_quarantined_at_utc");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_quarantined_payloads_rule_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_quarantined_payloads_source_id");

                    b.ToTable("quarantined_payloads", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Observations.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("attribute");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("claim_kind");

                    b.Property<string>("_caveats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("caveats");

                    b.HasKey("Id");

                    b.HasIndex("Attribute")
                        .HasDatabaseName("ix_observations_attribute");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Operations.Escalation", b =>
                {
                    b.Property<Guid>("EscalationId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at_utc");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<DateTime>("RaisedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reason");

                    b.Property<string>("Resolution")
                        .HasMaxLength(622)
                        .HasColumnType("character varying(622)")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at_utc");

                    b.HasKey("EscalationId");

                    b.HasIndex("ResolvedAtUtc", "ExpiresAtUtc")
                        .HasDatabaseName("ix_escalations_outstanding");

                    b.ToTable("escalations", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Operations.OperatingCycle", b =>
                {
                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("budget");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<string>("Consumption")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("consumption");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("EscalationCount")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_count");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("stage");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at_utc");

                    b.Property<string>("StoppedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stopped_reason");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template");

                    b.Property<string>("TriggerKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trigger_key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("WatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("watch_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CycleId");

                    b.HasIndex("TriggerKey")
                        .IsUnique()
                        .HasDatabaseName("ux_operating_cycles_trigger_key");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .HasDatabaseName("ix_operating_cycles_runnable");

                    b.HasIndex("WatchId", "StartedAtUtc")
                        .HasDatabaseName("ix_operating_cycles_watch");

                    b.ToTable("operating_cycles", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Opportunities.Opportunity", b =>
                {
                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovalTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_token_id");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Economics")
                        .HasColumnType("jsonb")
                        .HasColumnName("economics");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution");

                    b.Property<string>("Risk")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.Property<string>("_evidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("_proposalIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("proposal_ids");

                    b.HasKey("OpportunityId");

                    b.HasIndex("Status", "StatusChangedAtUtc")
                        .HasDatabaseName("ix_opportunities_status");

                    b.ToTable("opportunities", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Portfolio.PositionEvent", b =>
                {
                    b.Property<Guid>("PositionEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("change");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("instrument");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("quantity");

                    b.Property<string>("VenueReference")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("venue_reference");

                    b.HasKey("PositionEventId");

                    b.HasIndex("Instrument")
                        .HasDatabaseName("ix_position_events_instrument");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_position_events_occurred_at_utc");

                    b.HasIndex("VenueReference")
                        .IsUnique()
                        .HasDatabaseName("ux_position_events_venue_reference");

                    b.ToTable("position_events", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Retention.UnreplayableEvidence", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("MarkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("rule_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("MarkedAtUtc")
                        .HasDatabaseName("ix_unreplayable_evidence_marked_at_utc");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_unreplayable_evidence_source_id");

                    b.ToTable("unreplayable_evidence", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Shadow.ShadowDecision", b =>
                {
                    b.Property<Guid>("ShadowDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("ActualMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("actual_mode");

                    b.Property<string>("ActualOutcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actual_outcome");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_tier");

                    b.Property<string>("ShadowMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("shadow_mode");

                    b.Property<string>("ShadowOutcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("shadow_outcome");

                    b.HasKey("ShadowDecisionId");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("ix_shadow_decisions_recorded");

                    b.ToTable("shadow_decisions", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Sources.DataSource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("authority");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("region");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<string>("Reliability")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reliability");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("_categories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("categories");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_data_sources_is_active");

                    b.HasIndex("Region")
                        .HasDatabaseName("ix_data_sources_region");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Watching.Watch", b =>
                {
                    b.Property<Guid>("WatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<TimeSpan>("Cooldown")
                        .HasColumnType("interval")
                        .HasColumnName("cooldown");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CycleTemplate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cycle_template");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("disabled_reason");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("FireCount")
                        .HasColumnType("integer")
                        .HasColumnName("fire_count");

                    b.Property<DateTime?>("LastFiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fired_at_utc");

                    b.Property<TimeSpan>("MaxSignalAge")
                        .HasColumnType("interval")
                        .HasColumnName("max_signal_age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger_type");

                    b.HasKey("WatchId");

                    b.HasIndex("TriggerType", "Enabled")
                        .HasDatabaseName("ix_watches_trigger");

                    b.ToTable("watches", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Infrastructure.Persistence.KillSwitchFlag", b =>
                {
                    b.Property<Guid>("KillSwitchFlagId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("capability");

                    b.Property<bool>("Engaged")
                        .HasColumnType("boolean")
                        .HasColumnName("engaged");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("KillSwitchFlagId");

                    b.HasIndex("Capability")
                        .IsUnique()
                        .HasDatabaseName("ux_kill_switch_capability");

                    b.ToTable("kill_switch", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedup_key");

                    b.Property<DateTime?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_type");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OutboxMessageId");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_messages_dedup_key");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_outbox_messages_dispatch");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Infrastructure.Persistence.ProcessedAction", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("ClaimedAtUtc")
                        .HasDatabaseName("ix_processed_actions_claimed_at_utc");

                    b.ToTable("processed_actions", (string)null);
                });

            modelBuilder.Entity("AI.Investment.Domain.Approvals.ApprovalToken", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "MaxAmount", b1 =>
                        {
                            b1.Property<Guid>("ApprovalTokenId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("max_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("max_amount_currency");

                            b1.HasKey("ApprovalTokenId");

                            b1.ToTable("approval_tokens");

                            b1.WithOwner()
                                .HasForeignKey("ApprovalTokenId");
                        });

                    b.Navigation("MaxAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Autonomy.AutonomyGrant", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "MaxExposure", b1 =>
                        {
                            b1.Property<Guid>("AutonomyGrantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("max_exposure");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("max_exposure_currency");

                            b1.HasKey("AutonomyGrantId");

                            b1.ToTable("autonomy_grants");

                            b1.WithOwner()
                                .HasForeignKey("AutonomyGrantId");
                        });

                    b.Navigation("MaxExposure")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Autonomy.LiveVenueAuthorization", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "ExposureCeiling", b1 =>
                        {
                            b1.Property<Guid>("LiveVenueAuthorizationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("exposure_ceiling");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("exposure_ceiling_currency");

                            b1.HasKey("LiveVenueAuthorizationId");

                            b1.ToTable("live_venue_authorizations");

                            b1.WithOwner()
                                .HasForeignKey("LiveVenueAuthorizationId");
                        });

                    b.Navigation("ExposureCeiling")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Autonomy.PromotionWarrant", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "MaxExposure", b1 =>
                        {
                            b1.Property<Guid>("PromotionWarrantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("max_exposure");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("max_exposure_currency");

                            b1.HasKey("PromotionWarrantId");

                            b1.ToTable("promotion_warrants");

                            b1.WithOwner()
                                .HasForeignKey("PromotionWarrantId");
                        });

                    b.Navigation("MaxExposure")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Capital.LedgerEntry", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("ledger_entries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Capital.LedgerAccount", "Credit", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("credit_account_kind");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("credit_account");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("ledger_entries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Capital.LedgerAccount", "Debit", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("debit_account_kind");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("debit_account");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("ledger_entries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Credit")
                        .IsRequired();

                    b.Navigation("Debit")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Ingestion.IngestionRun", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.Ingestion.IngestionRequest", "Request", b1 =>
                        {
                            b1.Property<Guid>("IngestionRunId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("category");

                            b1.Property<string>("CorrelationId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("correlation_id");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("region");

                            b1.Property<DateTime>("RequestedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("requested_at_utc");

                            b1.Property<string>("SourceId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("source_id");

                            b1.HasKey("IngestionRunId");

                            b1.ToTable("ingestion_runs");

                            b1.WithOwner()
                                .HasForeignKey("IngestionRunId");

                            b1.OwnsOne("AI.Investment.Domain.Ingestion.IngestionSubject", "Subject", b2 =>
                                {
                                    b2.Property<Guid>("IngestionRequestIngestionRunId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Identifier")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("subject_identifier");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasMaxLength(60)
                                        .HasColumnType("character varying(60)")
                                        .HasColumnName("subject_kind");

                                    b2.HasKey("IngestionRequestIngestionRunId");

                                    b2.ToTable("ingestion_runs");

                                    b2.WithOwner()
                                        .HasForeignKey("IngestionRequestIngestionRunId");
                                });

                            b1.OwnsOne("AI.Investment.Domain.ValueObjects.DateRange", "Window", b2 =>
                                {
                                    b2.Property<Guid>("IngestionRequestIngestionRunId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("EndUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("window_end_utc");

                                    b2.Property<DateTime>("StartUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("window_start_utc");

                                    b2.HasKey("IngestionRequestIngestionRunId");

                                    b2.ToTable("ingestion_runs");

                                    b2.WithOwner()
                                        .HasForeignKey("IngestionRequestIngestionRunId");
                                });

                            b1.Navigation("Subject")
                                .IsRequired();

                            b1.Navigation("Window");
                        });

                    b.Navigation("Request")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Observations.Observation", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.Evidence.Provenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("ObservationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AsOfUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("as_of_utc");

                            b1.Property<DateTime>("PublishedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at_utc");

                            b1.Property<DateTime>("RetrievedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("retrieved_at_utc");

                            b1.Property<string>("SourceId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("source_id");

                            b1.Property<string>("SourceRecordId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("source_record_id");

                            b1.Property<string>("SourceUrl")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("source_url");

                            b1.HasKey("ObservationId");

                            b1.HasIndex("PublishedAtUtc")
                                .HasDatabaseName("ix_observations_published_at_utc");

                            b1.ToTable("observations");

                            b1.WithOwner()
                                .HasForeignKey("ObservationId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Ingestion.IngestionSubject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("ObservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Identifier")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subject_identifier");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("subject_kind");

                            b1.HasKey("ObservationId");

                            b1.HasIndex("Kind", "Identifier")
                                .HasDatabaseName("ix_observations_subject");

                            b1.ToTable("observations");

                            b1.WithOwner()
                                .HasForeignKey("ObservationId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Observations.ObservationValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("ObservationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Canonical")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("value");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("value_kind");

                            b1.HasKey("ObservationId");

                            b1.ToTable("observations");

                            b1.WithOwner()
                                .HasForeignKey("ObservationId");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();

                    b.Navigation("Subject")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Opportunities.Opportunity", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.Ingestion.IngestionSubject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Identifier")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("subject_identifier");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("subject_kind");

                            b1.HasKey("OpportunityId");

                            b1.HasIndex("Kind", "Identifier")
                                .HasDatabaseName("ix_opportunities_subject");

                            b1.ToTable("opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Opportunities.OpportunityDetail", "Detail", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("detail");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("detail_type");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Opportunities.OpportunityScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AsOfUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("score_as_of_utc");

                            b1.Property<string>("Metric")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("score_metric");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("score_value");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("score_version");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Opportunities.OpportunitySource", "Source", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DiscoveredAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("discovered_at_utc");

                            b1.Property<string>("DiscovererId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("discoverer_id");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.Navigation("Detail")
                        .IsRequired();

                    b.Navigation("Score");

                    b.Navigation("Source")
                        .IsRequired();

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Portfolio.PositionEvent", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "Fees", b1 =>
                        {
                            b1.Property<Guid>("PositionEventId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("fees");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("fees_currency");

                            b1.HasKey("PositionEventId");

                            b1.ToTable("position_events");

                            b1.WithOwner()
                                .HasForeignKey("PositionEventId");
                        });

                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("PositionEventId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("PositionEventId");

                            b1.ToTable("position_events");

                            b1.WithOwner()
                                .HasForeignKey("PositionEventId");
                        });

                    b.Navigation("Fees")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Shadow.ShadowDecision", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.ValueObjects.Money", "Exposure", b1 =>
                        {
                            b1.Property<Guid>("ShadowDecisionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("exposure");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("exposure_currency");

                            b1.HasKey("ShadowDecisionId");

                            b1.ToTable("shadow_decisions");

                            b1.WithOwner()
                                .HasForeignKey("ShadowDecisionId");
                        });

                    b.Navigation("Exposure")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Sources.DataSource", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.Sources.LicensingTerms", "Licensing", b1 =>
                        {
                            b1.Property<string>("DataSourceId")
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("AttributionRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("licence_attribution_required");

                            b1.Property<bool>("AutomatedProcessingAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("licence_processing_allowed");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("licence_notes");

                            b1.Property<bool>("RedistributionAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("licence_redistribution_allowed");

                            b1.Property<string>("Retention")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("licence_retention");

                            b1.Property<bool>("StorageAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("licence_storage_allowed");

                            b1.HasKey("DataSourceId");

                            b1.ToTable("data_sources");

                            b1.WithOwner()
                                .HasForeignKey("DataSourceId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Sources.UpdateCadence", "Cadence", b1 =>
                        {
                            b1.Property<string>("DataSourceId")
                                .HasColumnType("character varying(64)");

                            b1.Property<TimeSpan?>("ExpectedInterval")
                                .HasColumnType("interval")
                                .HasColumnName("cadence_interval");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("cadence_kind");

                            b1.HasKey("DataSourceId");

                            b1.ToTable("data_sources");

                            b1.WithOwner()
                                .HasForeignKey("DataSourceId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Sources.VerificationPolicy", "Verification", b1 =>
                        {
                            b1.Property<string>("DataSourceId")
                                .HasColumnType("character varying(64)");

                            b1.Property<bool>("CanConfirmAlone")
                                .HasColumnType("boolean")
                                .HasColumnName("verification_can_confirm_alone");

                            b1.Property<int>("RequiredIndependentSources")
                                .HasColumnType("integer")
                                .HasColumnName("verification_required_sources");

                            b1.HasKey("DataSourceId");

                            b1.ToTable("data_sources");

                            b1.WithOwner()
                                .HasForeignKey("DataSourceId");
                        });

                    b.Navigation("Cadence")
                        .IsRequired();

                    b.Navigation("Licensing")
                        .IsRequired();

                    b.Navigation("Verification")
                        .IsRequired();
                });

            modelBuilder.Entity("AI.Investment.Domain.Watching.Watch", b =>
                {
                    b.OwnsOne("AI.Investment.Domain.Watching.TriggerCondition", "Condition", b1 =>
                        {
                            b1.Property<Guid>("WatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Comparison")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("condition_comparison");

                            b1.Property<TimeSpan?>("Interval")
                                .HasColumnType("interval")
                                .HasColumnName("condition_interval");

                            b1.Property<decimal?>("Threshold")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("condition_threshold");

                            b1.HasKey("WatchId");

                            b1.ToTable("watches");

                            b1.WithOwner()
                                .HasForeignKey("WatchId");
                        });

                    b.OwnsOne("AI.Investment.Domain.Watching.WatchTarget", "Target", b1 =>
                        {
                            b1.Property<Guid>("WatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Identifier")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("target_identifier");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("target_kind");

                            b1.HasKey("WatchId");

                            b1.ToTable("watches");

                            b1.WithOwner()
                                .HasForeignKey("WatchId");
                        });

                    b.Navigation("Condition")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
